sudo: required
services:
  - docker
env:
  global:
# for using GIT_SHA id in deploy script for tagging images using GIT_SHA
  - GIT_SHA=$(git rev-parse HEAD)

before install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
#  - curl -o config https://$GITHUB_ACCESS_TOKEN@raw.githubusercontent.com/GithubOrganization/MySecretInfrastructureRepo/master/.kube/config
# here we get config file from AzS storage account, which URI is stored in Travis CI environment variable $AZS_SA_SAS_CONFIG
  - echo $AZS_SA_SAS_CONFIG_URL
  - curl -o config.tpl $AZS_SA_SAS_CONFIG_URL
  - curl $KUBE_CLUSTER_CERTIFICATE_URL | base64 -w0 > ca.crt
  - curl -o employee.crt $KUBE_CLIENT_CERTIFICATE_URL
  - curl -o employee.key $KUBE_CLIENT_KEY_URL
  - mkdir ${HOME}/.kube
  - cp config.tpl ${HOME}/.kube/config.tpl
  - cp ca.crt ${HOME}/.kube/
  - cp employee.crt ${HOME}/.kube/
  - cp employee.key ${HOME}/.kube/
# Fill out missing params in kubectl config file
  - export KUBE_CLUSTER_CERTIFICATE=$(cat $PWD/ca.crt)
  - export KUBE_CLIENT_CERTIFICATE=$PWD/employee.crt
  - export KUBE_CLIENT_KEY=$PWD/employee.key
#------------v--string below changeing variables in config.tpl file with values setted above and then write resulting file to the ${HOME}/.kube/config file
  - cat config.tpl | envsubst > ${HOME}/.kube/config
#  - cat ${HOME}/.kube/config
#  - echo $KUBECONFIG
#  - ls -al ${HOME}/.kube/
#  set credential to connect to cluster
  - kubectl config set-credentials employee --client-key=$PWD/employee.key --embed-certs=true
# set context for all subsequent kubectl commands to namespace 'office'
  - kubectl config set-context employee-context --cluster=AKSEngine --namespace=office --user=employee
  - kubectl config use-context employee-context
# for diagnostic - show resulting config 
  - kubectl config view
#  - kubectl --context=employee-context get pods
#  - kubectl --context=employee-context create secret generic pgpassword --from-literal PGPASSWORD="$PG_PASSWORD"
  
#login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  - docker build -t werton13/react-test -f ./client/Dockerfile.dev ./client

script:
# --------
  - docker run werton13/react-test npm test -- --coverage
#  - docker run -e CI=true w13/react-test npm run test
  
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
 




